import React, { useState, useEffect, useCallback } from 'react';
import { FiX, FiZap, FiCopy, FiCheck } from 'react-icons/fi';
import apiClient from '../../utils/axiosConfig';

const AISuggestionModal = ({ isOpen, onClose, onUseSuggestion, questionTitle, questionId }) => {
  const [aiAnswer, setAiAnswer] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  const fetchAISuggestion = useCallback(async () => {
    try {
      setLoading(true);
      setError('');
      const response = await apiClient.post('/api/ai/generate-answer', {
        questionId
      });
      setAiAnswer(response.data.answer || '');
    } catch (error) {
      console.error('Error fetching AI suggestion:', error);
      setError(error.response?.data?.message || 'Failed to generate AI suggestion. Please try again.');
    } finally {
      setLoading(false);
    }
  }, [questionId]);

  useEffect(() => {
    if (isOpen && questionId) {
      fetchAISuggestion();
    } else {
      setAiAnswer('');
      setError('');
    }
  }, [isOpen, questionId, fetchAISuggestion]);

  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
      return () => {
        document.body.style.overflow = 'unset';
      };
    }
  }, [isOpen]);

  // Handle ESC key
  useEffect(() => {
    const handleEsc = (e) => {
      if (e.key === 'Escape' && isOpen) {
        onClose();
      }
    };
    window.addEventListener('keydown', handleEsc);
    return () => window.removeEventListener('keydown', handleEsc);
  }, [isOpen, onClose]);


  const handleCopy = () => {
    // Get plain text from Quill editor
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = aiAnswer;
    const plainText = tempDiv.textContent || tempDiv.innerText || '';
    
    navigator.clipboard.writeText(plainText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleUseSuggestion = () => {
    if (onUseSuggestion && aiAnswer) {
      onUseSuggestion(aiAnswer);
      onClose();
    }
  };

  if (!isOpen) return null;

  return (
    <div 
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      onClick={(e) => {
        if (e.target === e.currentTarget) {
          onClose();
        }
      }}
    >
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/80 backdrop-blur-sm" onClick={onClose}></div>

      {/* Modal Content */}
      <div 
        className="relative w-full max-w-4xl bg-white dark:bg-gray-800 rounded-2xl shadow-2xl max-h-[90vh] flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-700">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gradient-to-br from-purple-500 to-pink-500 rounded-lg flex items-center justify-center">
              <FiZap className="w-5 h-5 text-white" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-gray-900 dark:text-white">
                AI Answer Suggestion
              </h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                {questionTitle}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
            aria-label="Close"
          >
            <FiX className="w-6 h-6" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {/* AI Disclaimer */}
          <div className="mb-4 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
            <div className="flex items-start gap-3">
              <FiZap className="w-5 h-5 text-blue-600 dark:text-blue-400 flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-semibold text-blue-900 dark:text-blue-200 mb-1">
                  AI-Generated Content
                </p>
                <p className="text-sm text-blue-700 dark:text-blue-300">
                  This answer was generated by AI and may contain errors or inaccuracies. 
                  Please review, verify, and edit before posting. Always verify technical details 
                  and ensure the answer is accurate and helpful.
                </p>
              </div>
            </div>
          </div>

          {loading ? (
            <div className="flex flex-col items-center justify-center py-12">
              <div className="w-12 h-12 border-4 border-primary border-t-transparent rounded-full animate-spin mb-4"></div>
              <p className="text-gray-600 dark:text-gray-400">Generating AI suggestion...</p>
            </div>
          ) : error ? (
            <div className="text-center py-12">
              <div className="text-red-500 mb-4">
                <FiZap className="w-12 h-12 mx-auto mb-2" />
              </div>
              <p className="text-red-600 dark:text-red-400 mb-4">{error}</p>
              <button
                onClick={fetchAISuggestion}
                className="px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors"
              >
                Try Again
              </button>
            </div>
          ) : aiAnswer ? (
            <div>
              <div className="mb-4 flex items-center justify-between">
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                  Suggested Answer
                </h3>
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-2 px-3 py-1.5 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
                >
                  {copied ? (
                    <>
                      <FiCheck className="w-4 h-4 text-green-500" />
                      <span>Copied!</span>
                    </>
                  ) : (
                    <>
                      <FiCopy className="w-4 h-4" />
                      <span>Copy</span>
                    </>
                  )}
                </button>
              </div>
              <div className="bg-gray-50 dark:bg-gray-900 rounded-lg p-4 border border-gray-200 dark:border-gray-700">
                <div 
                  className="prose dark:prose-invert max-w-none ql-editor"
                  dangerouslySetInnerHTML={{ __html: aiAnswer }}
                  style={{ minHeight: '200px', padding: '1rem' }}
                />
              </div>
            </div>
          ) : null}
        </div>

        {/* Footer */}
        {aiAnswer && !loading && !error && (
          <div className="flex items-center justify-end gap-3 p-6 border-t border-gray-200 dark:border-gray-700">
            <button
              onClick={onClose}
              className="px-4 py-2 text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleUseSuggestion}
              className="px-6 py-2 bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-lg hover:from-purple-600 hover:to-pink-600 transition-colors font-semibold flex items-center gap-2"
            >
              <FiZap className="w-4 h-4" />
              Use This Suggestion
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default AISuggestionModal;

